#!/usr/bin/env bash

# clone dotfiles repo
git clone git@github.com:placek/dotfiles.git $HOME/.config/dotfiles

# fetch vim plugins
pushd $HOME/.config/dotfiles
  git submodule init
  git submodule update
  pushd home
    stow --target=$HOME --verbose --stow *
  popd
popd

# install directories
mkdir -p $HOME/{Projects,Documents,Downloads,Clouds,Pictures,Music}

# rebuild xresources config
xrdb -merge .Xresources
