#!/usr/bin/env bash

# clone dotfiles repo
git clone --bare git@github.com:placek/dotfiles.git $HOME/.config/dotfiles

# set configuration to hide untracked files
git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME config --local status.showUntrackedFiles no

# "restore" files
git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME restore --staged $HOME
git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME restore $HOME

# ignore meta files
git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME update-index --skip-worktree $HOME/LICENSE
git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME update-index --skip-worktree $HOME/README.md
git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME update-index --skip-worktree $HOME/install
rm $HOME/LICENSE $HOME/README.md $HOME/install

# init submodules
rm -rf $HOME/.vim
git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME submodule init
git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME submodule update

# install directories
mkdir -p $HOME/{Projects,Documents,Downloads,Clouds,Pictures,Music}

# install fisher and fzf plugin
fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher && fisher install PatrickF1/fzf.fish"
