#!/usr/bin/env bash

case $1 in
  image)
    tiv -w $2 -h $3 -256 $4 2> /dev/null
    ;;
  video)
    thumbnail="$(mktemp).jpg"
    ffmpeg -i $4 -ss 00:00:01 -vframes 1 $thumbnail 2> /dev/null
    tiv -w $2 -h $3 -256 $thumbnail 2> /dev/null
    ;;
esac

