swipe:
  4:
    left:
      command: 'xdotool key super+Right'
    right:
      command: 'xdotool key super+Left'
  3:
    up:
      command: 'xdotool key super+n'
pinch:
  in:
    command: "xdotool key ctrl+plus"
  out:
    command: "xdotool key ctrl+minus"
